# Generated by Django 5.0.6 on 2024-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_category_options_category_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
